[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.4"
anyhow = "*"
thiserror = "*"

[dev-dependencies]
criterion = "*"
quickcheck = "*"
quickcheck_macros = "*"
